# Generated by Django 2.2.26 on 2023-05-11 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0007_auto_20230511_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 13, 22, 52, 382862)),
        ),
    ]
