# Generated by Django 2.2.26 on 2023-05-25 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0008_auto_20230511_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 25, 9, 14, 30, 781503)),
        ),
    ]
