# Generated by Django 2.2.26 on 2023-05-28 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0009_auto_20230525_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 13, 27, 21, 299331)),
        ),
    ]
