# Generated by Django 2.2.26 on 2023-06-03 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0011_auto_20230528_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='reseau',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 12, 31, 0, 900366)),
        ),
    ]
