# Generated by Django 2.2.26 on 2023-06-03 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0012_auto_20230603_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.AddField(
            model_name='machine',
            name='nom',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 12, 37, 43, 786244)),
        ),
    ]
