# Generated by Django 2.2.26 on 2023-06-03 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_auto_20230603_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='nom',
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 12, 38, 49, 403377)),
        ),
    ]
