# Generated by Django 2.2.26 on 2023-06-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0014_auto_20230603_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 12, 45, 45, 544799)),
        ),
    ]
