# Generated by Django 2.2.26 on 2023-06-04 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0016_auto_20230603_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 12, 58, 36, 24117)),
        ),
    ]
