# Generated by Django 2.2.26 on 2023-06-04 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0023_auto_20230604_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='mach',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='reseau',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 13, 36, 7, 382462)),
        ),
    ]
