# Generated by Django 2.2.26 on 2023-06-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0030_auto_20230604_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='reseau',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='machine',
            name='type_machine',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 14, 18, 22, 694762)),
        ),
    ]
