# Generated by Django 2.2.26 on 2023-06-06 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0031_auto_20230604_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.Machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 20, 35, 37, 256666)),
        ),
    ]
