# Generated by Django 2.2.26 on 2023-06-07 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0037_auto_20230606_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 20, 11, 6, 79293)),
        ),
    ]
